version: "3.7"
volumes:
  elasticsearch_data_external:
    external:
      name: elasticsearch_data
  elasticsearch_data:

  elasticsearch_backups_external:
    external:
      name: elasticsearch_backups
  elasticsearch_backups:

  status_storage_external:
    external:
      name: status_storage
  status_storage:

  prometheus_data_external:
    external:
      name: prometheus_data
  prometheus_data:

  grafana_data_external:
    external:
      name: grafana_data
  grafana_data:

  status_monitoring_data_external:
    external:
      name: status_monitoring_data
  status_monitoring_data:

  traefik_acme_certs_external:
    external:
      name: traefik_acme_certs
  traefik_acme_certs:

services:
  traefik:
    image: "traefik:1.7-alpine"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - type: bind
        source: ./traefik.toml
        target: /etc/traefik/traefik.toml
        read_only: true
      - type: bind
        source: ./monitoring_users_credentials.htdigest
        target: /srv/monitoring_users_credentials.htdigest
        read_only: true
      - type: volume
        source: traefik_acme_certs_external
        target: /acme_certs

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.6.0"
    environment:
      discovery.type: "single-node"
      cluster.name: "peertube-index-cluster"
      path.repo: "/backups"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    volumes:
      - type: volume
        source: elasticsearch_data_external
        target: /usr/share/elasticsearch/data
      - type: volume
        source: elasticsearch_backups_external
        target: /backups
    ulimits:
      memlock:
        soft: -1
        hard: -1

  webapp:
    image: "peertube-index/app:prod"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      STATUS_STORAGE_DIRECTORY: '/status_storage'
      HTTP_API_PORT: 80
    volumes:
      - type: volume
        source: status_storage_external
        target: /status_storage

  error-pages:
    image: "peertube-index/error-pages:prod"

  scan-loop:
    image: "peertube-index/app:prod"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      STATUS_STORAGE_DIRECTORY: '/status_storage'
      HTTP_API_PORT: 80
    volumes:
      - type: volume
        source: status_storage_external
        target: /status_storage
    entrypoint:
      - sh
      - scan_loop.sh

  seed-loop:
    image: "peertube-index/app:prod"
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      STATUS_STORAGE_DIRECTORY: '/status_storage'
      HTTP_API_PORT: 80
    volumes:
      - type: volume
        source: status_storage_external
        target: /status_storage
    entrypoint:
      - sh
      - seed_loop.sh

  status-monitoring-updater:
    image: "peertube-index/status-monitoring-updater:prod"
    depends_on:
      - status-monitoring-db
    volumes:
      - type: volume
        source: status_storage_external
        target: /status_storage
        read_only: true

  status-monitoring-db:
    image: "postgres:10"
    volumes:
      - type: volume
        source: status_monitoring_data_external
        target: /var/lib/postgresql/data

  prometheus:
    image: "prom/prometheus:v2.8.0"
    volumes:
      - type: volume
        source: prometheus_data_external
        target: /prometheus
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true

  grafana:
    image: "grafana/grafana:6.0.1"
    volumes:
      - type: volume
        source: grafana_data_external
        target: /var/lib/grafana

  node-exporter-relay:
    image: "peertube-index/node-exporter-relay:prod"
    volumes:
      - type: bind
        source: /tmp/node_exporter
        target: /node_exporter

  volume-migrate:
    image: "debian"
    entrypoint:
      - sleep
      - "604800" # 7 days
    volumes:
      - type: volume
        source: elasticsearch_data_external
        target: /volumes/elasticsearch_data_src
      - type: volume
        source: elasticsearch_data
        target: /volumes/elasticsearch_data_dst
      - type: volume
        source: elasticsearch_backups_external
        target: /volumes/elasticsearch_backups_src
      - type: volume
        source: elasticsearch_backups
        target: /volumes/elasticsearch_backups_dst
      - type: volume
        source: status_storage_external
        target: /volumes/status_storage_src
      - type: volume
        source: status_storage
        target: /volumes/status_storage_dst
      - type: volume
        source: prometheus_data_external
        target: /volumes/prometheus_data_src
      - type: volume
        source: prometheus_data
        target: /volumes/prometheus_data_dst
      - type: volume
        source: grafana_data_external
        target: /volumes/grafana_data_src
      - type: volume
        source: grafana_data
        target: /volumes/grafana_data_dst
      - type: volume
        source: status_monitoring_data_external
        target: /volumes/status_monitoring_data_src
      - type: volume
        source: status_monitoring_data
        target: /volumes/status_monitoring_data_dst
      - type: volume
        source: traefik_acme_certs_external
        target: /volumes/traefik_acme_certs_src
      - type: volume
        source: traefik_acme_certs
        target: /volumes/traefik_acme_certs_dst
