global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
    - targets: ['traefik:9090']

  - job_name: 'host-node-exporter-relay'
    static_configs:
    - targets: ['node-exporter-relay:9100']

  - job_name: 'grafana'
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
    - targets: ['grafana:3000']
