{
 "title": "Instances",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "# This dashboard shows aggregations on the current set of statuses. Statuses are updated every 5 minutes.\n\n"
  },
  {
   "title": "Status distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  status,\n  count(host),\n  round(100*count(host)::float/(SELECT count(*) FROM instance)) as \"%\"\nFROM instance\nGROUP BY status\n\n\n"
    }
   ]
  },
  {
   "title": "Oldest and newest statuses",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  status,\n  max(now() - date) as age_oldest,\n  EXTRACT(EPOCH FROM max(now() - date)) as age_oldest_in_seconds,\n  min(now() - date) as age_newest\nFROM instance\nWHERE status != 'banned'\nGROUP BY status"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN reason ~ '\\{:failed_connect, \\[\\{:to_address, .*'\n            THEN regexp_replace(reason, '(\\{:failed_connect, \\[\\{:to_address, \\{)(''.*'')(.*)', '\\1<hostname>\\3')\n        WHEN reason ~ '%Poison\\.ParseError.*'\n            THEN '%Poison.ParseError'\n        ELSE reason\n    END AS generic_reason,\n    count(host) as count,\n    round(100*count(host)::float/(SELECT count(*) FROM instance WHERE status = 'error')) as \"%\"\nFROM instance\nWHERE status = 'error'\nGROUP BY generic_reason;"
    }
   ]
  },
  {
   "title": "History of status distribution",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  import_time as time,\n  status as metric,\n  count as value\nFROM\n  history\nWHERE\n  $__timeFilter(import_time)\nORDER BY import_time ASC"
    }
   ]
  },
  {
   "title": "Number of instances over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  import_time as time,\n  'total' as metric,\n  sum(count) as value\nFROM\n  history\nWHERE\n  $__timeFilter(import_time)\nGROUP BY import_time\nORDER BY import_time ASC"
    }
   ]
  }
 ]
}