[file]

[accessLog]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true
    [entryPoints.http.auth.digest]
    usersFile = "/srv/users_credentials.htdigest"

[backends]
  [backends.peertube-index]
    [backends.peertube-index.servers.server1]
    url = "http://peertube-index:80"

[frontends]
  [frontends.peertube-index]
  backend = "peertube-index"
  [frontends.peertube-index.routes.get]
    rule = "Method: GET"
