{
 "title": "Traefik custom",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Request per status over one minute on HTTPS entrypoint",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(traefik_entrypoint_requests_total{entrypoint=\"https-public\"}[1m])",
     "legendFormat": "{{protocol}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Response time per status over 1 minute on HTTPS endpoint",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_request_duration_seconds_sum{entrypoint=\"https-public\"}[1m])/rate(traefik_entrypoint_request_duration_seconds_count{entrypoint=\"https-public\"}[1m])",
     "legendFormat": "{{protocol}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Request per status over one minute on HTTP endpoint",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(traefik_entrypoint_requests_total{entrypoint=\"http-public\"}[1m])",
     "legendFormat": "{{protocol}} {{method}} {{code}}"
    }
   ]
  }
 ]
}