global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
    - targets: ['peertube-index-traefik:9090']
